// <auto-generated />
using System;
using EntityFrameworkCore.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LearningManagementSystem.Db.Migrations
{
    [DbContext(typeof(LMSDbContext))]
    [Migration("20201204162222_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LearningManagementSystem.Domain.Model.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("StudentId");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Name = "Student 1"
                        },
                        new
                        {
                            StudentId = 2,
                            Name = "Student 2"
                        },
                        new
                        {
                            StudentId = 3,
                            Name = "Student 3"
                        },
                        new
                        {
                            StudentId = 4,
                            Name = "Student 4"
                        },
                        new
                        {
                            StudentId = 5,
                            Name = "Student 5"
                        },
                        new
                        {
                            StudentId = 6,
                            Name = "Student 6"
                        },
                        new
                        {
                            StudentId = 7,
                            Name = "Student 7"
                        },
                        new
                        {
                            StudentId = 8,
                            Name = "Student 8"
                        },
                        new
                        {
                            StudentId = 9,
                            Name = "Student 9"
                        },
                        new
                        {
                            StudentId = 10,
                            Name = "Student 10"
                        },
                        new
                        {
                            StudentId = 11,
                            Name = "Student 11"
                        },
                        new
                        {
                            StudentId = 12,
                            Name = "Student 12"
                        },
                        new
                        {
                            StudentId = 13,
                            Name = "Student 13"
                        },
                        new
                        {
                            StudentId = 14,
                            Name = "Student 14"
                        },
                        new
                        {
                            StudentId = 15,
                            Name = "Student 15"
                        },
                        new
                        {
                            StudentId = 16,
                            Name = "Student 16"
                        },
                        new
                        {
                            StudentId = 17,
                            Name = "Student 17"
                        },
                        new
                        {
                            StudentId = 18,
                            Name = "Student 18"
                        },
                        new
                        {
                            StudentId = 19,
                            Name = "Student 19"
                        },
                        new
                        {
                            StudentId = 20,
                            Name = "Student 20"
                        },
                        new
                        {
                            StudentId = 21,
                            Name = "Student 21"
                        },
                        new
                        {
                            StudentId = 22,
                            Name = "Student 22"
                        },
                        new
                        {
                            StudentId = 23,
                            Name = "Student 23"
                        },
                        new
                        {
                            StudentId = 24,
                            Name = "Student 24"
                        },
                        new
                        {
                            StudentId = 25,
                            Name = "Student 25"
                        },
                        new
                        {
                            StudentId = 26,
                            Name = "Student 26"
                        },
                        new
                        {
                            StudentId = 27,
                            Name = "Student 27"
                        },
                        new
                        {
                            StudentId = 28,
                            Name = "Student 28"
                        },
                        new
                        {
                            StudentId = 29,
                            Name = "Student 29"
                        },
                        new
                        {
                            StudentId = 30,
                            Name = "Student 30"
                        },
                        new
                        {
                            StudentId = 31,
                            Name = "Student 31"
                        },
                        new
                        {
                            StudentId = 32,
                            Name = "Student 32"
                        },
                        new
                        {
                            StudentId = 33,
                            Name = "Student 33"
                        },
                        new
                        {
                            StudentId = 34,
                            Name = "Student 34"
                        },
                        new
                        {
                            StudentId = 35,
                            Name = "Student 35"
                        },
                        new
                        {
                            StudentId = 36,
                            Name = "Student 36"
                        },
                        new
                        {
                            StudentId = 37,
                            Name = "Student 37"
                        },
                        new
                        {
                            StudentId = 38,
                            Name = "Student 38"
                        },
                        new
                        {
                            StudentId = 39,
                            Name = "Student 39"
                        },
                        new
                        {
                            StudentId = 40,
                            Name = "Student 40"
                        },
                        new
                        {
                            StudentId = 41,
                            Name = "Student 41"
                        },
                        new
                        {
                            StudentId = 42,
                            Name = "Student 42"
                        },
                        new
                        {
                            StudentId = 43,
                            Name = "Student 43"
                        },
                        new
                        {
                            StudentId = 44,
                            Name = "Student 44"
                        },
                        new
                        {
                            StudentId = 45,
                            Name = "Student 45"
                        },
                        new
                        {
                            StudentId = 46,
                            Name = "Student 46"
                        },
                        new
                        {
                            StudentId = 47,
                            Name = "Student 47"
                        },
                        new
                        {
                            StudentId = 48,
                            Name = "Student 48"
                        },
                        new
                        {
                            StudentId = 49,
                            Name = "Student 49"
                        },
                        new
                        {
                            StudentId = 50,
                            Name = "Student 50"
                        });
                });

            modelBuilder.Entity("LearningManagementSystem.Domain.Model.StudentSubject", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentSubject");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 7,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 7,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 8,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 8,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 9,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 9,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 10,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 10,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 11,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 11,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 12,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 12,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 13,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 13,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 14,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 14,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 15,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 15,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 16,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 16,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 17,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 17,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 18,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 18,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 19,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 19,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 20,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 20,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 21,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 21,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 22,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 22,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 23,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 23,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 24,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 24,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 25,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 25,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 26,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 26,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 27,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 27,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 28,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 28,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 29,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 29,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 30,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 30,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 31,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 31,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 32,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 32,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 33,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 33,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 34,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 34,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 35,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 35,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 36,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 36,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 37,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 37,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 38,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 38,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 39,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 39,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 40,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 40,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 41,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 41,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 42,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 42,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 43,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 43,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 44,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 44,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 45,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 45,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 46,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 46,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 47,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 47,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 48,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 48,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 49,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 49,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 50,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 50,
                            SubjectId = 5
                        });
                });

            modelBuilder.Entity("LearningManagementSystem.Domain.Model.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("SubjectId");

                    b.ToTable("Subject");

                    b.HasData(
                        new
                        {
                            SubjectId = 1,
                            Name = "Subject 1"
                        },
                        new
                        {
                            SubjectId = 2,
                            Name = "Subject 2"
                        },
                        new
                        {
                            SubjectId = 3,
                            Name = "Subject 3"
                        },
                        new
                        {
                            SubjectId = 4,
                            Name = "Subject 4"
                        },
                        new
                        {
                            SubjectId = 5,
                            Name = "Subject 5"
                        });
                });

            modelBuilder.Entity("LearningManagementSystem.Domain.Model.StudentSubject", b =>
                {
                    b.HasOne("LearningManagementSystem.Domain.Model.Student", "Student")
                        .WithMany("Subjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningManagementSystem.Domain.Model.Subject", "Subject")
                        .WithMany("Students")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
